"""Add company_name to jobs table

Revision ID: fccc5690dc47
Revises: 
Create Date: 2024-08-16 10:56:25.888710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccc5690dc47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobRole', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shortDescription', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('longDescription', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=False))
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('grade')
        batch_op.drop_column('longDescription')
        batch_op.drop_column('shortDescription')
        batch_op.drop_column('jobRole')

    # ### end Alembic commands ###
